msgid ""
msgstr "Content-Type: text/plain; charset=UTF-8"

#: TFORM1.CAPTION
msgid "Соединение pptp"
msgstr "Connection pptp"

#: TFORM1.MENUITEM1.CAPTION
msgid "Подключить"
msgstr ""

#: TFORM1.MENUITEM2.CAPTION
msgid "Отключить"
msgstr ""

#: unit1.message0
msgid "Внимание!"
msgstr "Attention!"

#: unit1.message10
msgid "Выход без ава#209�ии"
msgstr "Exit without problem"

#: unit1.message11
msgid "Выход п#209�и ава#209�ии"
msgstr "Exit with problem"

#: unit1.message2
msgid "Д#209�угая такая же п#209�ог#209�амма уже #209�аботает с VPN PPTP. Нажмите <OK> для отказа от двойного запуска."
msgstr "Another copy of program try configure VPN PPTP. Press <OK> for dismiss double run."

#: unit1.message3
msgid "Сначала сконфигу#209�и#209�уйте соединение: Меню, Утилиты, Системные (или Меню, Инте#209�нет), Наст#209�ойка VPN PPTP (Наст#209�ойка соединения VPN PPTP)."
msgstr "First configure connection: Menu, Tools, System (or Menu, Internet), Configure VPN PPTP."

#: unit1.message4
msgid "No ethernet. Cетевой инте#209�фейс для VPN PPTP недоступен. Если же он доступен, то установите \"Не конт#209�оли#209�овать state сетевого кабеля\" в Конфигу#209�ато#209�е."
msgstr "No ethernet. Network interface for VPN PPTP is not avalible. If it present, select \"Not control network cable state\" in Configurator."

#: unit1.message5
msgid "No link. Сетевой кабель для VPN PPTP неподключен."
msgstr "No link. Network cable for VPN PPTP is not connect."

#: unit1.message6
msgid "Соединение "
msgstr "Connection "

#: unit1.message7
msgid " установлено"
msgstr " is up"

#: unit1.message8
msgid " отсутствует"
msgstr " not avalible"

#: unit1.message9
msgid "No link. Сетевой кабель для VPN PPTP неподключен. А #209�еконнект не включен."
msgstr "No link. Network cable for VPN PPTP not connect. And reconnect is not on."

#: unit1.message12
msgid "Устанавливается соединение "
msgstr "Connecting "

#: unit1.message1
msgid "Запуск этой п#209�ог#209�аммы возможен только под админист#209�ато#209�ом или с #209�аз#209�ешения админист#209�ато#209�а. Нажмите <OK> для отказа от запуска."
msgstr "The start of this program is possible only as root or with root's permission. Press <OK> for exit."

#: unit1.message13
msgid "Получены ма#209�ш#209�уты по DHCP. "
msgstr "Get routes via DHCP. "

#: unit1.message14
msgid "Обна#209�ужен новый ip-ад#209�ес vpn-се#209�ве#209�а. Соединение пе#209�енаст#209�аивается... "
msgstr "Found a new ip-address vpn server. Connection is reconfigured... "

#: unit1.message15
msgid "Vpn-се#209�ве#209� не пингуется. "
msgstr "Vpn server does not ping. "

#: unit1.message16
msgid "Доступ в инте#209�нет отсутствует..."
msgstr "No Internet access available..."

#: unit1.message17
msgid "DNS-се#209�ве#209� до поднятия VPN не отвечает или неко#209�#209�ектный ад#209�ес vpn-се#209�ве#209�а. "
msgstr "DNS server before raise VPN is not responding or incorrect address vpn server. "

#: unit1.message18
msgid "Шлюз локальной сети не пингуется. "
msgstr "The local network gate is not pinged. "

#: unit1.message19
msgid "П#209�ове#209�ено! Инте#209�нет #209�аботает!"
msgstr "Сhecked! The Internet is working!"

#: unit1.message20
msgid "Обна#209�ужено совпадение remote ip address с ip-ад#209�есом самого vpn-се#209�ве#209�а. Соединение было пе#209�енаст#209�оено."
msgstr "Found to match with the remote ip address ip-address of the vpn-server. The connection has been reconfigured."

#: unit1.message21
msgid "Ошибка получения ма#209�ш#209�утов по DHCP. "
msgstr "Failed to get routes via DHCP."

#: unit1.message23
msgid "DNS1-се#209�ве#209� до поднятия VPN не пингуется. "
msgstr "DNS1-server before raise VPN does not ping. "

#: unit1.message24
msgid "DNS2-се#209�ве#209� до поднятия VPN не пингуется. "
msgstr "DNS2-server before raise VPN does not ping. "
